disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - function_body_length
  - function_parameter_count
  - identifier_name
  - class_delegate_protocol
  - force_cast
  - file_length
  - large_tuple

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - MyPoint/Common/Libs
  - MyPoint/Personal/Introduction
  - MyPoint/Vouchers/VoucherDetail/VoucherDetailViewController.swift 

#Custom
identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
type_name:
  min_length: 1
  max_length:
    warning: 50
    error: 60
line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
